### ISSUE TITLE
【论文复现赛验收ISSUE】

### ISSUE THREAD

**Issue by huangjun12** [flytocc/CycleMLP-paddle#1]
1. 看精度较验收标准差了0.9个点，看看再提升一下精度呢？ 一般可接受波动范围约为0.5个点

**Comment by flytocc** [comment]
不好意思，repo里标的精度写错了，我复现的精度是79.02，比验收标准高。可查看训练的log验证。

________________________________
发件人: huangjun12 ***@***.***>
发送时间: 2022年4月21日 11:20
收件人: flytocc/CycleMLP-paddle ***@***.***>
抄送: Subscribed ***@***.***>
主题: [flytocc/CycleMLP-paddle] 【论文复现赛验收ISSUE】 (Issue #1)


  1.  看精度较验收标准差了0.9个点，看看再提升一下精度呢？ 一般可接受波动范围约为0.5个点

―

**Comment by flytocc** [comment]
> 1. 看精度较验收标准差了0.9个点，看看再提升一下精度呢？ 一般可接受波动范围约为0.5个点
